AWSTemplateFormatVersion: '2010-09-09'

Description: CloudMart temporary database schema migration stack

Parameters:

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:

  SchemaMigrationRole:
    Type: AWS::IAM::Role

    Properties:

      RoleName:
        !Sub CloudMart-${Environment}-Schema-Migration-Role

      AssumeRolePolicyDocument:

        Version: '2012-10-17'

        Statement:

          - Effect: Allow

            Principal:
              Service:
                - lambda.amazonaws.com

            Action:
              - sts:AssumeRole

      ManagedPolicyArns:

        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      Policies:

        - PolicyName: SchemaMigrationSSMAccess

          PolicyDocument:

            Version: '2012-10-17'

            Statement:

              - Effect: Allow

                Action:
                  - ssm:GetParameter

                Resource:

                  - !Sub
                    - arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cloudmart/${Environment}/database/host
                    - {}

                  - !Sub
                    - arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cloudmart/${Environment}/database/port
                    - {}

                  - !Sub
                    - arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cloudmart/${Environment}/database/name
                    - {}

                  - !Sub
                    - arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cloudmart/${Environment}/database/username
                    - {}

                  - !Sub
                    - arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cloudmart/${Environment}/database/password
                    - {}

  SchemaMigrationLambda:
    Type: AWS::Lambda::Function

    Properties:

      FunctionName:
        !Sub CloudMart-${Environment}-SchemaMigration

      Runtime: python3.12

      Handler: index.lambda_handler

      Role:
        !GetAtt SchemaMigrationRole.Arn

      Timeout: 120

      MemorySize: 256

      VpcConfig:

        SecurityGroupIds:

          - Fn::ImportValue:
              !Sub CloudMart-${Environment}-LambdaSecurityGroupId

        SubnetIds:

          - Fn::ImportValue:
              !Sub CloudMart-${Environment}-PrivateSubnetId

          - Fn::ImportValue:
              !Sub CloudMart-${Environment}-PrivateSubnet2Id

      Environment:

        Variables:

          ENVIRONMENT:
            !Ref Environment

      Code:

        S3Bucket:
          Fn::ImportValue:
            !Sub CloudMart-${Environment}-ReportsBucketName

        S3Key:
          schema/schema-lambda.zip

Outputs:

  SchemaMigrationLambdaArn:

    Description: Temporary schema migration Lambda ARN

    Value:
      !GetAtt SchemaMigrationLambda.Arn

